import 'package:flutter_test/flutter_test.dart';
import 'package:masrouf/core/money/currency.dart';
import 'package:masrouf/core/money/money.dart';
import 'package:masrouf/core/time/ym.dart';
import 'package:masrouf/data/local/app_database.dart';
import 'package:masrouf/domain/entities/account.dart';
import 'package:masrouf/domain/entities/category.dart';
import 'package:masrouf/domain/entities/txn.dart';
import 'package:masrouf/domain/enums/txn_type.dart';

import '../helpers/test_database.dart';

/// The baseline behind the forecast. Two things have to hold or the projection
/// is quietly wrong: rows a recurring rule generated must be excluded (they are
/// counted again as commitments), and months before the user existed must not
/// be read as months they spent nothing.
void main() {
  late AppDatabase db;
  const userId = 'user-1';
  const base = Currency.tnd;

  Txn expense(
    String id,
    int milli,
    DateTime date, {
    String? ruleId,
    TxnType type = TxnType.expense,
  }) =>
      Txn(
        id: id,
        type: type,
        amount: Money(milli, base),
        fxRateToBase: 1,
        categoryId: 'cat-groceries',
        accountId: 'acc-cash',
        transferAccountId: null,
        date: date,
        note: null,
        tags: const <String>[],
        recurringRuleId: ruleId,
        createdAt: date,
        updatedAt: date,
      );

  setUp(() async {
    db = openTestDatabase();
    await db.accountDao.upsert(
      userId,
      Account(
        id: 'acc-cash',
        name: 'Cash',
        type: AccountType.cash,
        currency: base,
        openingBalance: const Money(1000000, base),
        sortOrder: 0,
        archived: false,
        updatedAt: DateTime.now(),
      ),
    );
    await db.categoryDao.upsertAll(userId, <Category>[
      Category(
        id: 'cat-groceries',
        name: 'Groceries',
        kind: CategoryKind.expense,
        icon: 'groceries',
        color: 0xFF2A78D6,
        sortOrder: 0,
        isDefault: true,
        updatedAt: DateTime.now(),
      ),
    ]);
  });

  tearDown(() => db.close());

  const months = <Ym>[
    Ym.of(2026, 6),
    Ym.of(2026, 7),
    Ym.of(2026, 8),
  ];

  test('rows generated by a recurring rule are excluded', () async {
    await db.transactionDao
        .insertTxn(userId, expense('t1', 40000, DateTime(2026, 7, 5)), base);
    // Rent, produced by a rule. Counted as a commitment in the projection, so
    // including it here would charge the user twice for it every month.
    await db.transactionDao.insertTxn(
      userId,
      expense('t2', 500000, DateTime(2026, 7, 5), ruleId: 'rule-rent'),
      base,
    );

    final byMonth = await db.analyticsDao
        .spontaneousExpenseByMonth(userId, months, base);

    expect(byMonth[const Ym.of(2026, 7).value], 40000);
  });

  test('income and expense are counted separately', () async {
    await db.transactionDao
        .insertTxn(userId, expense('t1', 40000, DateTime(2026, 7, 5)), base);
    await db.transactionDao.insertTxn(
      userId,
      expense('t2', 900000, DateTime(2026, 7, 1), type: TxnType.income),
      base,
    );

    final expenses = await db.analyticsDao
        .spontaneousExpenseByMonth(userId, months, base);
    final income = await db.analyticsDao
        .spontaneousIncomeByMonth(userId, months, base);

    expect(expenses[const Ym.of(2026, 7).value], 40000);
    expect(income[const Ym.of(2026, 7).value], 900000);
  });

  test('a month with nothing in it reports zero, not a missing key', () async {
    await db.transactionDao
        .insertTxn(userId, expense('t1', 40000, DateTime(2026, 7, 5)), base);

    final byMonth = await db.analyticsDao
        .spontaneousExpenseByMonth(userId, months, base);

    expect(byMonth.keys.toSet(), months.map((m) => m.value).toSet());
    expect(byMonth[const Ym.of(2026, 6).value], 0);
    expect(byMonth[const Ym.of(2026, 8).value], 0);
  });

  test('a deleted row stops counting toward the baseline', () async {
    final txn = expense('t1', 40000, DateTime(2026, 7, 5));
    await db.transactionDao.insertTxn(userId, txn, base);
    await db.transactionDao.softDeleteTxn(userId, txn, base);

    final byMonth = await db.analyticsDao
        .spontaneousExpenseByMonth(userId, months, base);

    expect(byMonth[const Ym.of(2026, 7).value], 0);
  });

  test('rows outside the window are not counted', () async {
    await db.transactionDao
        .insertTxn(userId, expense('t1', 40000, DateTime(2026, 3, 5)), base);

    final byMonth = await db.analyticsDao
        .spontaneousExpenseByMonth(userId, months, base);

    expect(byMonth.values.every((v) => v == 0), isTrue);
  });

  test('an empty month list is answered without a query', () async {
    expect(
      await db.analyticsDao
          .spontaneousExpenseByMonth(userId, const <Ym>[], base),
      isEmpty,
    );
  });

  /// Someone who started this month has no completed history at all. A
  /// projection of zero is technically true and useless — the month in progress
  /// is scaled up instead, and the result stays labelled provisional.
  test('the month in progress is pro-rated when there is no history', () async {
    final now = DateTime.now();
    final thisMonth = Ym.fromDate(now);

    await db.transactionDao.insertTxn(
      userId,
      expense('t1', 30000, DateTime(now.year, now.month, 1)),
      base,
    );

    final byMonth = await db.analyticsDao
        .spontaneousExpenseByMonth(userId, <Ym>[thisMonth], base);

    expect(
      byMonth[thisMonth.value],
      30000,
      reason: 'the current month is queryable, which the fallback relies on',
    );
    final completed = await db.analyticsDao.spontaneousExpenseByMonth(
      userId,
      thisMonth.previous.lastMonths(6),
      base,
    );
    // Every completed month is empty, which is what triggers the fallback.
    expect(completed.values, everyElement(0));
  });
}
