import 'package:flutter_test/flutter_test.dart';
import 'package:masrouf/core/money/currency.dart';
import 'package:masrouf/core/money/money.dart';
import 'package:masrouf/core/result/result.dart';
import 'package:masrouf/data/local/app_database.dart';
import 'package:masrouf/data/repositories/transaction_repository_impl.dart';
import 'package:masrouf/domain/entities/account.dart';
import 'package:masrouf/domain/entities/category.dart';
import 'package:masrouf/domain/entities/txn.dart';
import 'package:masrouf/domain/enums/txn_type.dart';
import 'package:masrouf/domain/repositories/repositories.dart';

import '../helpers/app_harness.dart';
import '../helpers/test_database.dart';

/// The history selection bar's bulk paths and swipe-to-duplicate.
///
/// The interesting failure mode here is aggregate corruption: the DAO folds
/// every write into the derived tables, so deleting an already-deleted row or
/// restoring a live one would count its amount twice in opposite directions.
/// The double-delete / double-restore assertions pin exactly that.
void main() {
  late AppDatabase db;
  late TransactionRepository repository;

  Txn expense({
    required String id,
    required int milli,
    String categoryId = 'cat-groceries',
    DateTime? date,
    List<String> tags = const <String>[],
    String? ruleId,
  }) =>
      Txn(
        id: id,
        type: TxnType.expense,
        amount: Money(milli, Currency.tnd),
        fxRateToBase: 1,
        categoryId: categoryId,
        accountId: 'acc-cash',
        transferAccountId: null,
        date: date ?? DateTime(2026, 9, 10),
        note: null,
        tags: tags,
        recurringRuleId: ruleId,
        createdAt: DateTime(2026, 9, 10),
        updatedAt: DateTime(2026, 9, 10),
      );

  Future<int> cashBalance() async {
    final rows = await (db.select(db.accountBalances)
          ..where((t) => t.accountId.equals('acc-cash')))
        .get();
    return rows.single.balanceMilli;
  }

  setUp(() async {
    db = openTestDatabase();
    await seedMinimalLedger(db);
    await db.accountDao.upsert(
      testUser.id,
      Account(
        id: 'acc-bank',
        name: 'Bank',
        type: AccountType.bank,
        currency: Currency.tnd,
        openingBalance: const Money.zero(Currency.tnd),
        sortOrder: 1,
        archived: false,
        updatedAt: DateTime.now(),
      ),
    );
    await db.categoryDao.upsertAll(testUser.id, <Category>[
      Category(
        id: 'cat-salary',
        name: 'Salary',
        kind: CategoryKind.income,
        icon: 'salary',
        color: 0xFF0F7B3E,
        sortOrder: 0,
        isDefault: false,
        updatedAt: DateTime.now(),
      ),
    ]);
    repository = TransactionRepositoryImpl(
      db: db,
      sync: testSyncEngine(db),
      userId: testUser.id,
      base: Currency.tnd,
    );
  });

  tearDown(() async => db.close());

  group('duplicate', () {
    test('copies the row with a fresh id and clears the rule link', () async {
      final source = expense(id: 't1', milli: 25000, ruleId: 'rule-1');
      await repository.add(source);

      final copy = await repository.duplicate('t1');
      expect(copy, isA<Ok<Txn>>());

      final created = (copy as Ok<Txn>).value;
      expect(created.id, isNot('t1'));
      expect(created.amount, source.amount);
      expect(created.categoryId, 'cat-groceries');
      // The copy was made by hand, not generated by the rule.
      expect(created.recurringRuleId, isNull);

      // The balance has seen the original and its copy.
      expect(await cashBalance(), 100000 - 25000 - 25000);
    });

    test('a missing source is a notFound failure, not a crash', () async {
      final result = await repository.duplicate('nope');
      expect(result, isA<Err<Txn>>());
    });
  });

  group('recategorize', () {
    test('moves expenses and skips rows the category kind cannot own',
        () async {
      await repository.add(expense(id: 'e1', milli: 1000));
      await repository.add(expense(id: 'e2', milli: 2000));
      await repository.add(Txn(
        id: 'i1',
        type: TxnType.income,
        amount: const Money(50000, Currency.tnd),
        fxRateToBase: 1,
        categoryId: 'cat-salary',
        accountId: 'acc-cash',
        transferAccountId: null,
        date: DateTime(2026, 9, 10),
        note: null,
        tags: const <String>[],
        recurringRuleId: null,
        createdAt: DateTime(2026, 9, 10),
        updatedAt: DateTime(2026, 9, 10),
      ));

      final result = await repository.recategorize(
        <String>['e1', 'e2', 'i1'],
        'cat-salary', // an income category
      );

      // Only the already-income row could take an income category; it is
      // already filed there, so nothing changes at all.
      expect((result as Ok<int>).value, 0);
      expect(await cashBalance(), 100000 - 1000 - 2000 + 50000);

      final moved = await repository.recategorize(
        <String>['e1', 'e2', 'i1'],
        'cat-groceries', // an expense category
      );
      // The income row is skipped; both expenses are already there.
      expect((moved as Ok<int>).value, 0);
    });

    test('an unknown category fails without touching rows', () async {
      await repository.add(expense(id: 'e1', milli: 1000));
      final result = await repository.recategorize(
        <String>['e1'],
        'cat-ghost',
      );
      expect(result, isA<Err<int>>());
      expect(await cashBalance(), 100000 - 1000);
    });
  });

  group('addTag', () {
    test('normalises and skips rows that already carry the tag', () async {
      await repository.add(expense(id: 'e1', milli: 1000));
      await repository.add(expense(id: 'e2', milli: 2000, tags: <String>['fees']));

      final first = await repository.addTag(<String>['e1', 'e2'], ' Fees ');
      // e2 already has the normalised tag, so only e1 changed.
      expect((first as Ok<int>).value, 1);

      final again = await repository.addTag(<String>['e1', 'e2'], 'fees');
      expect((again as Ok<int>).value, 0);

      expect((await repository.getById('e1'))!.tags, <String>['fees']);
      expect((await repository.getById('e2'))!.tags, <String>['fees']);
    });
  });

  group('deleteMany / restoreMany', () {
    test('deletes a batch, undoes it whole, and guards against re-apply',
        () async {
      await repository.add(expense(id: 'e1', milli: 1000));
      await repository.add(expense(id: 'e2', milli: 2000));
      await repository.add(expense(id: 'e3', milli: 4000));

      final deleted =
          await repository.deleteMany(<String>['e1', 'e2', 'ghost']);
      expect((deleted as Ok<int>).value, 2);
      expect(await cashBalance(), 100000 - 4000);

      // A second delete of a tombstoned row must not subtract it again.
      final again = await repository.deleteMany(<String>['e1']);
      expect((again as Ok<int>).value, 0);
      expect(await cashBalance(), 100000 - 4000);

      final restored = await repository.restoreMany(<String>['e1', 'e2']);
      expect((restored as Ok<int>).value, 2);
      // e3 is still live, so all three expenses are charged again.
      expect(await cashBalance(), 100000 - 7000);

      // Restoring a live row must not add it again either.
      final onceMore = await repository.restoreMany(<String>['e1']);
      expect((onceMore as Ok<int>).value, 0);
      expect(await cashBalance(), 100000 - 7000);
    });
  });
}
